### ISSUE TITLE
Allow tukhs with only two shabads (words) to be searched using first-letter

### ISSUE THREAD

**Issue by irvanjit** [KhalisFoundation/ShabadOS-API#17]
Suggestions:
-extend first-letter indices for these tukhs (probably makes more sense)
-add exceptions to the min 3-char limit (i.e. when searching Dasam Bani)
https://www.sikhitothemax.org/ang?ang=16&source=D
https://www.sikhitothemax.org/ang?ang=1&source=D

**Comment by ManjotS** [comment]
My feeling on this is we can find all lines with only 2 words and then
include the first letters from the line before and the line after.. that
way a search will find them.

**Comment by tarunsingh5** [comment]
what if you just order the results by the number of words in the line_id

**Comment by tarunsingh5** [comment]
to be more specific, make the requirement 2 letters and also order by number of words in the line_id

**Comment by irvanjit** [comment]
keeping the requirement 3 letters helps narrow down results. doesn't make sense to change that requirement when it works well for most of gurbani.

**Comment by tarunsingh5** [comment]
yea but you can order by short sentences when the user puts in 2 letters, and keep current functionality for 3 letters or more

**Comment by ManjotS** [comment]
I don't think we should change the api, this can be done on front end.

**Comment by ManjotS** [comment]
according to @tarunsingh5 if search length is less than 3 letters, api should prioritize shorter results first

**Comment by ManjotS** [comment]
commit edcd4f94619f95fab8bdbcfe087f2891b7f20e19 should fix this but needs to be tested
