### ISSUE TITLE
Lots of mistakes in Dasam Bani

### ISSUE THREAD

**Issue by irvanjit** [KhalisFoundation/ShabadOS-API#18]
There's a few in swaayae, suspect there's probably more elsewhere.
https://www.sikhitothemax.org/ang?ang=13&source=D

**Comment by ManjotS** [comment]
@irvanjit can you make these concrete submissions to the api control panel?

**Comment by ManjotS** [comment]
@tarunsingh5 does this need to stay open?

**Comment by tarunsingh5** [comment]
nope this has been fixed largely
