### ISSUE TITLE
Minor Translations Mistakes

### ISSUE THREAD

**Issue by inderpreet99** [KhalisFoundation/ShabadOS-API#19]
On the following line in https://www.sikhitothemax.org/shabad?id=1143, the translation word should be `near`.

    Those who become Gurmukh avoid him; they forsake his company and sit **hear** the Guru.

On the following line in https://www.sikhitothemax.org/shabad?id=2513, the translation word should be `quilt`.

    ask for a quit to cover myself.

**Comment by ManjotS** [comment]
Submitted changes to the API backend:

https://www.shabados.org/control-panel/?approve=13851&changeid=75
https://www.shabados.org/control-panel/?approve=28406&changeid=76
