### ISSUE TITLE
Translation doesn't match

### ISSUE THREAD

**Issue by vikramkhalsa** [KhalisFoundation/ShabadOS-API#8]
https://www.sikhitothemax.org/shabad?id=40308&q=vnAgp&type=1&source=all

Translation for the line 
ਵਾਲਹੁ ਨਿਕਾ ਆਖੀਐ ਗੁਰ ਪੰਥੁ ਨਿਰਾਲਾ।
Which perishes everything, and the ill-advised intellect is the abode of evil deeds.

Doesn't make sense in my opinion. I'm not sure what translation would be, maybe check another source?
Something along the lines of "The unique path of the Guru is thinner than a strand of hair"...

**Comment by ManjotS** [comment]
Submitted to ShabadOS https://www.shabados.org/control-panel/?approve=202596&changeid=73
