### ISSUE TITLE
exbilarated is not a word

### ISSUE THREAD

**Issue by karamheen** [KhalisFoundation/ShabadOS-API#9]
From Tarun:
found an issue on sttm.org

[9:28]  
rUp Apwr lKY inRp ko purbwisn kO aupijXo suK Bwro ]
Seeing the handsomeness of the Raja, the inhabitants were feeling exbilarated.

[9:28]  
exbilarated is not a word

**Comment by ManjotS** [comment]
https://www.shabados.org/control-panel/?approve=117465&changeid=74
